name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 10
          - 12
          - 14
          - 16
          - 18
          - 20

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm i

    - name: Lint, test, and build
      run: npm start validate

    - name: Check test coverage
      uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
