name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - name: Close Stale Issues and PRs
        uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Stale issue'
          stale-pr-message: 'Stale pull request'
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
